name: CI-CD React Lessons

# Creating a trigger which tells githubActions when to run our workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# list of jobs to include in our workflow, and we defin the OS we want our job to run on
jobs:
  build_test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm test
      - run: npm run build

  push_to_Docker:
    needs: [build_test]
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-projects:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/react-projects:latest
          run: |
            echo "running docker image"
